#after_success: coveralls
cache: pip
install:
  - pip install coveralls flake8 pydocstyle
  - python setup.py install
language: python
matrix:
  allow_failures:
    - python: nightly
  fast_finish: true
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly
sudo: false
script:
  - flake8 --exclude=docs
  - pydocstyle pyrow
  - coverage run --source=pyrow setup.py test